import type { Metadata } from 'next'
import { type ILayout } from '../types/layout'
import { Inter } from 'next/font/google'
import { Header } from '@/widget/Header'
import { Footer } from '@/widget/Footer/ui/Footer'
import StoreProvider from '../providers/StoreProvider'

import '../styles/globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: ILayout) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StoreProvider>
                    <section id="App">
                        <Header />
                        {children}
                        <Footer />
                    </section>
                </StoreProvider>
            </body>
        </html>
    )
}

export default RootLayout
